---
- name: HW1
  hosts: hw1

  tasks:

  - name: Checkout git repository
    ansible.builtin.git:
      repo: 'https://github.com/Mattliahkim/HW0Files.git'
      dest: /root/meme
  - name: Start server
    command: node meme/server/server.js
